apiVersion: v1
kind: Namespace
metadata:
  name: secplay

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-playground
  namespace: secplay
  labels:
    app: security-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-playground
  template:
    metadata:
      labels:
        app: security-playground
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
      containers:
      - name: security-playground
        image: ghcr.io/andrewd-sysdig/security-playground:latest
        env:
        - name: PGHOST
          value: "appdb"
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          value: "postgres"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: security-playground
  name: secplay
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: security-playground
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdb
  namespace: secplay
  labels:
    app: appdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdb
  template:
    metadata:
      labels:
        app: appdb
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
      containers:
      - name: appdb
        image: aa8y/postgres-dataset:latest
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: appdb
  name: appdb
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: appdb
  type: ClusterIP